version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: install node deps
          command: |
            ls ~/app/src/screens
            npm install

      - run: npm run test-ci
