version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo
    environment:
      JAVA_HOME: "/opt/jdk"


    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install deps
          command: |
            sudo npm i -g react-native-cli create-react-native-app
            npm install

      - run:
          name: install jdk
          command: |
            # Install cURL
            apk --no-cache add curl ca-certificates tar

            # Java Version
            export JAVA_VERSION_MAJOR=8
            export JAVA_VERSION_MINOR=45
            export JAVA_VERSION_BUILD=14
            export JAVA_PACKAGE=jdk

            # Download and unarchive Java
            sudo mkdir /opt
            sudo curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" \
              http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/${JAVA_PACKAGE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz > jdk.tgz
            sudo tar -xzf jdk.tgz -C /opt
            sudo ln -s /opt/jdk1.${JAVA_VERSION_MAJOR}.0_${JAVA_VERSION_MINOR} /opt/jdk
            sudo rm -rf /opt/jdk/*src.zip \
              /opt/jdk/lib/missioncontrol \
              /opt/jdk/lib/visualvm \
              /opt/jdk/lib/*javafx* \
              /opt/jdk/jre/lib/plugin.jar \
              /opt/jdk/jre/lib/ext/jfxrt.jar \
              /opt/jdk/jre/bin/javaws \
              /opt/jdk/jre/lib/javaws.jar \
              /opt/jdk/jre/lib/desktop \
              /opt/jdk/jre/plugin \
              /opt/jdk/jre/lib/deploy* \
              /opt/jdk/jre/lib/*javafx* \
              /opt/jdk/jre/lib/*jfx* \
              /opt/jdk/jre/lib/amd64/libdecora_sse.so \
              /opt/jdk/jre/lib/amd64/libprism_*.so \
              /opt/jdk/jre/lib/amd64/libfxplugins.so \
              /opt/jdk/jre/lib/amd64/libglass.so \
              /opt/jdk/jre/lib/amd64/libgstreamer-lite.so \
              /opt/jdk/jre/lib/amd64/libjavafx*.so \
              /opt/jdk/jre/lib/amd64/libjfx*.so

      - save_cache:
          paths:
            - node_modules
            - /usr/local/lib/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      # try to build for android
      - run: PATH=${PATH}:${JAVA_HOME}/bin npm run android

      # try to build for ios
      - run: npm run ios


